# Generated by Django 3.2.9 on 2021-11-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='班级ID')),
                ('class_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '班级表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程ID')),
                ('course_name', models.CharField(max_length=30, verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('role', models.CharField(choices=[('0', 'Student'), ('1', 'Teacher')], default=0, max_length=30)),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.user', verbose_name='教师ID')),
            ],
            options={
                'verbose_name': '教师',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sims.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.user', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '学生',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sims.course')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sims.student')),
            ],
            options={
                'verbose_name': '分数表',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sims.teacher', verbose_name='课程号'),
        ),
    ]
