# Generated by Django 3.2.9 on 2021-11-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to='sims.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='sims.user', verbose_name='学生ID'),
        ),
    ]
