# Generated by Django 3.2.9 on 2021-11-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0002_auto_20211111_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='sims.user', verbose_name='学生ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sims.user', verbose_name='教师ID'),
        ),
    ]
