# Generated by Django 3.2.9 on 2021-11-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_auto_20211112_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
