# Generated by Django 3.2.9 on 2021-11-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_auto_20211112_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='sims.teacher', to_field='teacher_id', verbose_name='课程号'),
        ),
    ]
