# Generated by Django 3.2.9 on 2021-11-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sims.student')),
            ],
        ),
    ]
