# Generated by Django 3.2.9 on 2021-11-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_authtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authtoken',
            options={'verbose_name': 'Token 表'},
        ),
    ]
