# Generated by Django 3.2.9 on 2021-11-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_alter_authtoken_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='score',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='sims.user'),
        ),
    ]
