# Generated by Django 3.2.9 on 2021-11-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0008_auto_20211112_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
