# Generated by Django 3.2.9 on 2021-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0011_auto_20211113_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
