# Generated by Django 3.2.9 on 2021-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0012_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Teacher'), ('1', 'Student')], default=0, max_length=30),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
